update: rollback feature on github workflow

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -12,12 +12,16 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+      
+      - name: Backup current image
+        run: |
+          docker tag re-wild-oasis:current re-wild-oasis:backup || true
 
-      - name: Build Docker image
+      - name: Build new docker image
         run: |
           docker build \
             --secret id=env,src=/home/venom/Projects/re-wild-oasis/.env \
-            -t re-wild-oasis:current .
+            -t re-wild-oasis:new .
 
       - name: Stop existing container
         run: |
@@ -30,9 +34,10 @@ jobs:
             --name re-wild-oasis \
             --restart unless-stopped \
             -p 8082:80 \
-            re-wild-oasis:current
+            re-wild-oasis:new
 
-      - name: Check container
+      - name: Health check
+        id: health
         run: |
           echo "Waiting for application startup..."
           sleep 5
@@ -40,3 +45,23 @@ jobs:
           curl --fail http://localhost:8082
 
           echo "Application is healthy"
+      
+      - name: Promote new image
+        if: success()
+        run: |
+          docker tag re-wild-oasis:new re-wild-oasis:current
+          docker rmi re-wild-oasis:new || true
+      
+      - name: Rollback on failure
+        if: failure()
+        run: |
+          echo: 'Deployment failed. Rolling back...'
+
+          docker stop re-wild-oasis || true
+          docker rm re-wild-oasis || true
+
+          docker run -d \
+            --name re-wild-oasis \
+            --restart unless-stopped \
+            -p 8082:80 \
+            re-wild-oasis:backup
